-- 24 órán belül jelentkezett valamilyen állásra álláskeresők neve
SELECT (VEZNEV || ' ' || KERNEV) as NEV FROM ((ALLASKERESO A
    INNER JOIN FELHASZNALO F ON F.ID = A.FEID)
    INNER JOIN JELENTKEZES J ON J.ALLID = A.ID)
    WHERE J.MIKOR > CURRENT_TIMESTAMP - interval '1' day;

-- Munkaadók felhasználóneve legalább 2 hírdetéssel
SELECT FELHNEV FROM (SELECT FELHNEV, COUNT(H.ID) as darab FROM ((MUNKAADO M
    INNER JOIN FELHASZNALO F on F.ID = M.FEID)
    LEFT JOIN HIRDETESFELADAS H ON H.MUID = M.ID)
    GROUP BY FELHNEV) WHERE darab > 1;

-- Álláskeresők neve legalább 1 szakmával
SELECT NEV FROM (SELECT (F.VEZNEV || ' ' || F.KERNEV) as NEV, COUNT(B.ALLID) as darab
    FROM ((ALLASKERESO A
    INNER JOIN FELHASZNALO F on F.ID = A.FEID)
    LEFT JOIN BIRTOKOL B on B.ALLID = A.ID)
    GROUP BY VEZNEV, KERNEV) WHERE darab > 0;

-- Legnépszerűbb szakmák
SELECT NEV, COUNT(B.ALLID) as DARAB
    FROM SZAKMAK SZ INNER JOIN BIRTOKOL B on SZ.ID = B.SZAKID
    GROUP BY NEV;

-- Felhasználónak megfelelő szakmák. KELL BELE ID
SELECT H.NEV FROM HIRDETESEK H
    INNER JOIN SZAKMAK SZ ON LOWER(H.NEV) = LOWER(SZ.NEV)
    INNER JOIN BIRTOKOL B on SZ.ID = B.SZAKID
    INNER JOIN ALLASKERESO A on B.ALLID = A.ID
    WHERE A.FEID = ':id';

-- Hírdetés a legtöbb jelentkezővel
SELECT * FROM (
    SELECT NEV, LEIRAS, MAX(J.ID) as JELENTKEZOK
    FROM HIRDETESEK H
    INNER JOIN JELENTKEZES J on H.ID = J.HIID
    GROUP BY NEV, LEIRAS
) ORDER BY JELENTKEZOK DESC;

-- A legfiatalabb álláskereső
SELECT VEZNEV, KERNEV, FELHNEV, EMAIL, VAROS, UTCA, HAZSZAM, TELEFON, MAX(A.SZULIDO) as SZULETESI_IDO FROM ALLASKERESO A
    INNER JOIN FELHASZNALO F on A.FEID = F.ID
    WHERE SZULIDO = (SELECT MAX(SZULIDO) from ALLASKERESO)
    GROUP BY VEZNEV, KERNEV, FELHNEV, EMAIL, VAROS, UTCA, HAZSZAM, TELEFON;